### ISSUE TITLE
messed up button functions

### ISSUE THREAD

**Issue by panislepickova** [pavelpatrin/trinder#5]
This otherwise **great** app has a flaw: ```<div class="history__action-actions">
            <button class="btn history__action-btn history__action-btn-pass" ng-click="like(action.person)" ng-disabled="!action.person.id">👎 Pass</button>
            <button class="btn history__action-btn history__action-btn-like" ng-click="pass(action.person)" ng-disabled="!action.person.id">👍 Like</button>
            <button class="btn history__action-btn history__action-btn-superlike" ng-click="like(action.person)" ng-disabled="!action.person.id">🌟 Super</button>
        </div>``` should be ```<div class="history__action-actions">
            <button class="btn history__action-btn history__action-btn-pass" ng-click="pass(action.person)" ng-disabled="!action.person.id">👎 Pass</button>
            <button class="btn history__action-btn history__action-btn-like" ng-click="like(action.person)" ng-disabled="!action.person.id">👍 Like</button>
            <button class="btn history__action-btn history__action-btn-superlike" ng-click="superlike(action.person)" ng-disabled="!action.person.id">🌟 Super</button>
        </div>```, unless we want to troll the users.. 😀

**Comment by pavelpatrin** [comment]
Oh lol. Thank you.

**Comment by pavelpatrin** [comment]
Do somethig wothout complete release cycle is always bad idea...

**Comment by pavelpatrin** [comment]
Fixed in 0.3.3, and possible related bug fixed in 0.3.4.
